---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzite-dms
description: A personal BlueBuild recipe for a bazzite-gnome-nvidia-open flavor with Dank Material Shell.

base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - avengemedia/dms
        - avengemedia/danklinux
    install:
      packages:
        - cliphist
        - danksearch
        - dgop
        - dms
        - dms-greeter
        - ghostty
        - material-symbols-fonts
        - matugen
        - niri
        - quickshell
        - xwayland-satellite

  - type: systemd
    system:
      enabled:
        - greetd
      disabled:
        - gdm
    user:
      enabled: []

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

